services:
  mongodb:
    image: mongo:8.0
    container_name: mongoserver
    restart: always
    ports:
      - "27018:27017"  # Expose MongoDB internally at 27017, externally at 27018
    volumes:
      - /mongo_data:/data/db
    networks:
      - backend

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: soccar-api
    restart: always
    ports:
      - "8080:8080"  # Expose your Go API
    environment:
      - MONGO_URI=mongodb://mongodb:27017   # Connect to Mongo service via docker network
      - REDIS_URL=redis:6379
      - RAPIDAPI_PROXY_SECRET=${RAPIDAPI_PROXY_SECRET}
    depends_on:
      - mongodb
      - redis
    networks:
      - backend

  redis:
    image: redis:alpine
    container_name: redisserver
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /redis_volume_data:/data
    networks:
      - backend

volumes:
  mongo_data:
  redis_volume_data:

networks:
  backend:
    driver: bridge
