version: "3.9"

services:
  api:
    build: .
    container_name: football-api
    ports:
      - "8080:8080"
    environment:
      - REDIS_ADDR=redis:6379
      - MONGO_URI=mongodb://mongodb-server:27017
      - PORT=8080
    depends_on:
      - redis
      - mongodb-server
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  mongodb:
    image: mongo:8.0
    container_name: mongodb-server
    ports:
      - "27017:27017"
    restart: unless-stopped
